name: Usable Differential Privacy at UVM
short_name: UDP @ UVM
description: Human-centered research on making differential privacy understandable, useful, and usable in practice.
url: https://usable-differential-privacy.github.io
baseurl: ""
base: ""

permalink: /news/:year/:month/:day/:title/

roles:
  - key: faculty
    name: Faculty Principal Investigators
  - key: grad
    name: PhD Students

collections:
  research:
    output: false

navigation:
  - title: Home
    link: /
  - title: People
    link: /people/
  - title: Research
    link: /research.html
  - title: Publications
    link: /publications.html
  - title: Resources
    link: /resources.html

exclude:
  - README.md
  - Makefile
  - screenshot.png
  - LICENSE

sass:
  style: compressed

defaults:
  - scope:
      path: ""
    values:
      layout: default
